version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger_pipeline:
    type: boolean
    default: true
  build_and_deploy_image:
    type: boolean
    default: true

executors:
  node:
    docker:
      - image: circleci/python:3.7

jobs:
  build_and_deploy_image:
    parameters:
      package_version:
        type: string
      env_name:
        type: string
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project/
    steps:
      - when:
        condition: << pipeline.parameters.build_and_deploy_image >>
        steps:
          - checkout:
              path: ~/project
          - run:
              name: build image
              command: |
                echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
                pip install google_compute_engine
                gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
                gcloud --quiet config set project ${GCP_PROJECT}
                echo "Build ..."
                docker build --rm=false -t us.gcr.io/${GCP_PROJECT}/lid_model:<< parameters.package_version >> -t us.gcr.io/${GCP_PROJECT}/lid_model:<< parameters.package_version >> .
          - run:
            name: deploy image to registry
            command: |
              gcloud docker -- push us.gcr.io/${GCP_PROJECT}/lid_model
          - run:
            name: Remove account details
            command: rm ${HOME}/gcp-key.json ; ls
      - unless:
          condition: << pipeline.parameters.build_and_deploy_image >>
          steps:
            - run:
                name: image deployment not set to true
                command: |
                  echo 'Image not deployed'


workflows:
  version: 2

  build_and_deploy_image:
    when: << pipeline.parameters.trigger_pipeline >>
    jobs:
      - build_and_deploy_image
      - filters:
          branches:
            only: mlops